name: Build firmware
# Don't enable CI on push, just on PR. If you
# are working on the main repo and want to trigger
# a CI build submit a draft PR.
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y install zip build-essential
      - name: Setup environment
        run: |
          # This is the hash of the commit for the PR
          # when the action is triggered by PR, empty otherwise
          COMMIT_ID=${{ github.event.pull_request.head.sha }}
          # This is the hash of the commit when triggered by push
          # but the hash of refs/pull/<n>/merge, which is different
          # from the hash of the latest commit in the PR, that's
          # why we try github.event.pull_request.head.sha first
          COMMIT_ID=${COMMIT_ID:-${{ github.sha }}}
          BUILD_SUFFIX=ci-$(date '+%Y%m%d')-$(git rev-parse --short ${COMMIT_ID})
          VERSION=$(make print-version)
          echo "BUILD_SUFFIX=${BUILD_SUFFIX}" >> $GITHUB_ENV
          echo "BUILD_NAME=LuaTelemetry-${VERSION}-${BUILD_SUFFIX}" >> $GITHUB_ENV
      - name: Build dist
        run: make dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ env.BUILD_NAME }}.zip
          path: ./dist/*.zip

  test:
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
      - name: Run
        run: true
